spring.application.name=myapp
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.name=My application
info.app.description=Provide English root
info.app.version=0.0.1