spring.application.name=myapp
spring.application.author.name=Khang Phan

server.port=8090

management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.name=My application
info.app.description=Provide English root
info.app.version=0.0.1

spring.security.user.name=admin
spring.security.user.password=admin7890