spring.application.name=myapp
spring.application.author.name=Khang Phan

spring.main.lazy-initialization=true

spring.security.user.name=admin
spring.security.user.password=admin7890

server.port=8090

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=My application
info.app.description=Provide English root
info.app.version=0.0.1

spring.datasource.url=jdbc:postgresql://localhost:5432/student_tracker
spring.datasource.username=admin_spring
spring.datasource.password=p@ssw0rd123

#spring.main.banner-mode=off

# Standard Spring Data JPA property to show SQL
spring.jpa.show-sql=true

# Format the SQL so it's not a single long line (Human-readable)
spring.jpa.properties.hibernate.format_sql=true

# log for sql statement
#logging.level.root=warn
logging.level.org.hibernate.sql=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

# configure hibernate to automatically create db
spring.jpa.hibernate.ddl-auto=update

# spring rest configuration
spring.data.rest.base-path=/api/v2
spring.data.rest.default-page-size=20

logging.level.org.springframework.security=DEBUG

# swagger
#springdoc.swagger-ui.path=/my-ui.html
#springdoc.api-docs.path=/my-api-docs

#liquibase
# Disable automatic execution on startup
spring.liquibase.enabled=false

# Point to your master YAML changelog
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Database Credentials (referencing your primary datasource)
spring.liquibase.url=${spring.datasource.url}
spring.liquibase.user=${spring.datasource.username}
spring.liquibase.password=${spring.datasource.password}
